import { join } from "node:path";
import type { CliContext } from "../cli/context.js";
import type { CliDiagnostic } from "../cli/diagnostics.js";
import { cliDiagnostic } from "../cli/diagnostics.js";
import { normalizeAbsolutePath } from "../project/source-cache.js";

export const ADD_MACHINE_STORE_PATHS = {
  createMachine: "src/store/create-machine.ts",
  index: "src/store/index.ts",
  types: "src/store/types.ts",
  machinesDirectory: "src/store/machines",
} as const;

export type AddMachineStoreSnapshot = {
  rootPath: string;
  createMachinePath: string;
  machinesDirectoryPath: string;
  index: {
    relativePath: typeof ADD_MACHINE_STORE_PATHS.index;
    absolutePath: string;
    source: string;
  };
  types: {
    relativePath: typeof ADD_MACHINE_STORE_PATHS.types;
    absolutePath: string;
    source: string;
  };
};

export type ReadAddMachineStoreResult =
  | { ok: true; store: AddMachineStoreSnapshot }
  | { ok: false; diagnostics: CliDiagnostic[] };

export const addMachineProjectPath = (cwd: string, relativePath: string): string => {
  return normalizeAbsolutePath(join(cwd, relativePath));
};

const missingStoreDiagnostic = (cwd: string, message: string): CliDiagnostic => {
  return cliDiagnostic("LFC_ADD_MACHINE_STORE_NOT_FOUND", "error", message, {
    file: addMachineProjectPath(cwd, "src/store"),
    hint: "Run this command from a project generated by lite-fsm create.",
  });
};

export const readAddMachineStore = (context: CliContext): ReadAddMachineStoreResult => {
  const createMachinePath = addMachineProjectPath(context.cwd, ADD_MACHINE_STORE_PATHS.createMachine);
  const indexPath = addMachineProjectPath(context.cwd, ADD_MACHINE_STORE_PATHS.index);
  const typesPath = addMachineProjectPath(context.cwd, ADD_MACHINE_STORE_PATHS.types);
  const machinesDirectoryPath = addMachineProjectPath(context.cwd, ADD_MACHINE_STORE_PATHS.machinesDirectory);
  const missing: string[] = [];

  if (!context.fs.fileExists(createMachinePath)) missing.push(ADD_MACHINE_STORE_PATHS.createMachine);
  if (!context.fs.fileExists(indexPath)) missing.push(ADD_MACHINE_STORE_PATHS.index);
  if (!context.fs.fileExists(typesPath)) missing.push(ADD_MACHINE_STORE_PATHS.types);
  if (!context.fs.directoryExists(machinesDirectoryPath)) missing.push(ADD_MACHINE_STORE_PATHS.machinesDirectory);

  if (missing.length > 0) {
    return {
      ok: false,
      diagnostics: [
        missingStoreDiagnostic(context.cwd, `Generated lite-fsm store was not found. Missing: ${missing.join(", ")}.`),
      ],
    };
  }

  try {
    return {
      ok: true,
      store: {
        rootPath: addMachineProjectPath(context.cwd, "src/store"),
        createMachinePath,
        machinesDirectoryPath,
        index: {
          relativePath: ADD_MACHINE_STORE_PATHS.index,
          absolutePath: indexPath,
          source: context.fs.readFile(indexPath),
        },
        types: {
          relativePath: ADD_MACHINE_STORE_PATHS.types,
          absolutePath: typesPath,
          source: context.fs.readFile(typesPath),
        },
      },
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);

    return {
      ok: false,
      diagnostics: [
        missingStoreDiagnostic(context.cwd, `Generated lite-fsm store could not be read: ${message}`),
      ],
    };
  }
};
