export const VISUALIZER_TEST_IDS = {
  shell: {
    root: "visualizer-shell",
    topbar: "visualizer-topbar",
    workspace: "visualizer-workspace",
  },
  tabs: {
    root: "visualizer-tabs",
    trigger: {
      source: "visualizer-tab-source",
      system: "visualizer-tab-system",
      events: "visualizer-tab-events",
      machines: "visualizer-tab-machines",
    },
  },
  source: {
    panel: "visualizer-source-panel",
    search: "visualizer-source-search",
    reset: "visualizer-source-reset",
    editor: "visualizer-source-editor",
    snippet: "visualizer-source-snippet",
    overlay: "visualizer-source-overlay",
    overlayClose: "visualizer-source-overlay-close",
    overlayFallback: "visualizer-source-overlay-fallback",
    open: "visualizer-source-open",
    summary: "visualizer-source-summary",
    status: "visualizer-source-status",
  },
  system: {
    panel: "visualizer-system-panel",
    machineSearch: "visualizer-system-machine-search",
    topicSearch: "visualizer-system-topic-search",
    machineList: "visualizer-system-machine-list",
    topicList: "visualizer-system-topic-list",
    details: "visualizer-system-details",
    viewSource: "visualizer-system-view-source",
    openInWorkbench: "visualizer-system-open-workbench",
    openInEvents: "visualizer-system-open-events",
  },
  events: {
    panel: "visualizer-events-panel",
    search: "visualizer-events-search",
    list: "visualizer-events-list",
    details: "visualizer-events-details",
    routingValues: "visualizer-events-routing-values",
    producers: "visualizer-events-producers",
    consumers: "visualizer-events-consumers",
    viewSource: "visualizer-events-view-source",
  },
  workbench: {
    panel: "visualizer-workbench-panel",
    eventSearch: "visualizer-workbench-event-search",
    eventSourceSelect: "visualizer-workbench-event-source-select",
    machineCard: "visualizer-workbench-machine-card",
    sourceAction: "visualizer-workbench-source-action",
    currentState: "visualizer-workbench-current-state",
    longLabel: "visualizer-workbench-long-label",
    row: {
      config: "visualizer-workbench-row-config",
      effect: "visualizer-workbench-row-effect",
      simulation: "visualizer-workbench-row-simulation",
    },
  },
  console: {
    toggle: "visualizer-console-toggle",
    backdrop: "visualizer-console-backdrop",
    panel: "visualizer-console-panel",
    close: "visualizer-console-close",
    channels: "visualizer-console-channels",
    channelAll: "visualizer-console-channel-all",
    channelSystem: "visualizer-console-channel-system",
    channelDiagnostics: "visualizer-console-channel-diagnostics",
    channelDebug: "visualizer-console-channel-debug",
    entries: "visualizer-console-entries",
    analyzerAlert: "visualizer-console-analyzer-alert",
    simulatorAlert: "visualizer-console-simulator-alert",
    timeline: "visualizer-console-timeline",
    timelineSend: "visualizer-console-timeline-send",
    timelineStep: "visualizer-console-timeline-step",
  },
} as const;
