export const VISUALIZER_TEST_IDS = {
  shell: {
    root: "visualizer-shell",
    topbar: "visualizer-topbar",
    workspace: "visualizer-workspace",
  },
  tabs: {
    root: "visualizer-tabs",
    trigger: {
      source: "visualizer-tab-source",
      system: "visualizer-tab-system",
      events: "visualizer-tab-events",
      machines: "visualizer-tab-machines",
    },
  },
  source: {
    panel: "visualizer-source-panel",
    search: "visualizer-source-search",
    reset: "visualizer-source-reset",
    editor: "visualizer-source-editor",
    snippet: "visualizer-source-snippet",
    overlay: "visualizer-source-overlay",
    overlayClose: "visualizer-source-overlay-close",
    overlayFooterClose: "visualizer-source-overlay-footer-close",
    overlayTitle: "visualizer-source-overlay-title",
    overlayDescription: "visualizer-source-overlay-description",
    overlayFallback: "visualizer-source-overlay-fallback",
    open: "visualizer-source-open",
    summary: "visualizer-source-summary",
    status: "visualizer-source-status",
  },
  system: {
    panel: "visualizer-system-panel",
    machineSearch: "visualizer-system-machine-search",
    topicSearch: "visualizer-system-topic-search",
    machineList: "visualizer-system-machine-list",
    machineRow: "visualizer-system-machine-row",
    machineEmpty: "visualizer-system-machine-empty",
    topicList: "visualizer-system-topic-list",
    topicRow: "visualizer-system-topic-row",
    topicEmpty: "visualizer-system-topic-empty",
    topicChip: "visualizer-system-topic-chip",
    details: "visualizer-system-details",
    detailEmpty: "visualizer-system-detail-empty",
    detailMachine: "visualizer-system-detail-machine",
    detailTopic: "visualizer-system-detail-topic",
    detailConsumedTopics: "visualizer-system-detail-consumed-topics",
    detailProducedTopics: "visualizer-system-detail-produced-topics",
    detailProducers: "visualizer-system-detail-producers",
    detailConsumers: "visualizer-system-detail-consumers",
    viewSource: "visualizer-system-view-source",
    openInWorkbench: "visualizer-system-open-workbench",
    openInEvents: "visualizer-system-open-events",
  },
  events: {
    panel: "visualizer-events-panel",
    search: "visualizer-events-search",
    list: "visualizer-events-list",
    topicRow: "visualizer-events-topic-row",
    listEmpty: "visualizer-events-list-empty",
    details: "visualizer-events-details",
    detailEmpty: "visualizer-events-detail-empty",
    detailTopic: "visualizer-events-detail-topic",
    routingValues: "visualizer-events-routing-values",
    routingValue: "visualizer-events-routing-value",
    producers: "visualizer-events-producers",
    producerRow: "visualizer-events-producer-row",
    consumers: "visualizer-events-consumers",
    consumerRow: "visualizer-events-consumer-row",
    consumerBranch: "visualizer-events-consumer-branch",
    viewSource: "visualizer-events-view-source",
  },
  workbench: {
    panel: "visualizer-workbench-panel",
    status: "visualizer-workbench-status",
    notice: "visualizer-workbench-notice",
    metricMachines: "visualizer-workbench-metric-machines",
    metricTopics: "visualizer-workbench-metric-topics",
    metricDiagnostics: "visualizer-workbench-metric-diagnostics",
    eventSearch: "visualizer-workbench-event-search",
    eventSourceSelect: "visualizer-workbench-event-source-select",
    machineCard: "visualizer-workbench-machine-card",
    sourceAction: "visualizer-workbench-source-action",
    currentState: "visualizer-workbench-current-state",
    longLabel: "visualizer-workbench-long-label",
    row: {
      config: "visualizer-workbench-row-config",
      effect: "visualizer-workbench-row-effect",
      simulation: "visualizer-workbench-row-simulation",
    },
  },
  console: {
    toggle: "visualizer-console-toggle",
    backdrop: "visualizer-console-backdrop",
    panel: "visualizer-console-panel",
    close: "visualizer-console-close",
    channels: "visualizer-console-channels",
    channelAll: "visualizer-console-channel-all",
    channelSystem: "visualizer-console-channel-system",
    channelDiagnostics: "visualizer-console-channel-diagnostics",
    channelDebug: "visualizer-console-channel-debug",
    entries: "visualizer-console-entries",
    entry: "visualizer-console-entry",
    analyzerAlert: "visualizer-console-analyzer-alert",
    simulatorAlert: "visualizer-console-simulator-alert",
    timeline: "visualizer-console-timeline",
    timelineSend: "visualizer-console-timeline-send",
    timelineStep: "visualizer-console-timeline-step",
  },
} as const;
